### ISSUE TITLE
Getting started troubles

### ISSUE THREAD

**Issue by WebShapedBiz** [remult/crm-demo#2]
Hi guys.

This is my first attempt to learn Remult but I'm having issues with starting the app as you can see here:
![ksnip_20230426-143628](https://user-images.githubusercontent.com/6765137/234577567-0693b2eb-7a8a-40b4-a210-e252207c70e8.png)

Also, in your installation instructions, there is this line: `You can now view crm-demo in the browser:http://localhost:3000` but, as you can see, in terminal I'm getting the link for port 5173.

My node version is 16.14.1.

Thank you for your time and effort.

**Comment by noam-honig** [comment]
Fixd

**Comment by noam-honig** [comment]
Fixed it, can you please check and let us know?

**Comment by WebShapedBiz** [comment]
Thank you very much @noam-honig, it works fine now :-)
