### ISSUE TITLE
Updating dependencies breaks the app.

### ISSUE THREAD

**Issue by alexchern** [remult/crm-demo#4]
Hi Noam,

Cloning the app and running it works. Updating the dependencies (npm update) leads to varios errors when trying to run or build it.
Just to let you know...

Thanks,

Alex

**Comment by noam-honig** [comment]
Thanks - I'm on it

**Comment by noam-honig** [comment]
Hi @alexchern, fixed it in latest commit - needed to update a few stuff with @mui and replace ts-node-dev with tsx

**Comment by alexchern** [comment]
Work like a charm... Thanks.
P.S.  
I've sent you a message on Linked (a question about deployment, which does not belong here...) If you have a minute, can you call me at 0544563650?
